name: vial build
on:
  workflow_dispatch:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/*'

jobs:
  compile-vial:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
    env:
      USERSPACE_PATH: users/${{ github.actor }}

    steps:
    - name: Checkout VIAL QMK
      uses: actions/checkout@v4
      with:
        repository: vial-kb/vial-qmk
        ref: vial
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v4
      with:
        path: ${{ env.USERSPACE_PATH }}
        persist-credentials: false

    - name: Setup safe directory
      run: git config --global --add safe.directory '*'

    - name: Install rsync
      run:  apt-get update; apt-get install -y rsync

    - name: Copy firmware files
      run: rsync -av ${{ env.USERSPACE_PATH }}/firmware/travaulta keyboards/

    - name: compile vial
      run: make travaulta:vial

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        retention-days: 60
        name: vial_firmware
        path: |
          *.hex
          *.bin
          *.uf2

  commit-and-push:
    needs: compile-vial
    steps:
    - name: Checkout userspace
      uses: actions/checkout@v4

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: firmware
        pattern: vial_firmware*

    - run: ls -R firmware

    - uses: EndBug/add-and-commit@v9
      with:
        add: 'firmware'
        message: 'generated by github workflow'
        cwd: '${{ env.USERSPACE_PATH }}'
